// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Re-run `npm run optimize:images` after replacing any campaign master.

export interface CampaignAsset {
  width: number;
  height: number;
  lqip: string;
}

export const CAMPAIGN_ASSETS: Record<string, CampaignAsset> = {
  "opening": {
    "width": 1920,
    "height": 2880,
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwBQCdASoYACQAPu1mqk2ppiQiMBqqqTAdiWMAyrQWbUBVwB+P6JZ1/lOd2Y1nJbTiUQZWduQXQAD+6La8EtwPF3YECrHci1oTvSd9YCcpf4w0dnlSyLIXq3OR7fICBPzSQpeKq6ECjDcK3TjDdGeXUp/UMfjUuCae2KlZX3mf1YyH+mr3IrZ/NWbxnQeXMvz2x5N4lqiKUAAA"
  },
  "closing": {
    "width": 1920,
    "height": 1280,
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBdgMXmb7S2DpLCp2X4caB9dAAD+5zKqygCMRj79txfoztsm97W0ZLUpsQrq5pFcP2eMm/K49L+BKkyx08WIzrIqgjoFWoiXHRbvAvymOlyFdmzvziyO+MsF73r/j/f1TbwDydb58ymeObgyIQ+nitvrczfvau8lV9x3avmIo0e0tIkWGMY0AAA="
  },
  "season": {
    "width": 1920,
    "height": 2875,
    "lqip": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAABwBwCdASoYACQAPuVapU2pJKOiNVgMASAciWwAv2s9w+D2QZqnV0sX5VAn0TNVbvGvTWn3My/asKoHLY5NT1LM8q4NAAD+7N38ejO6JGq7HQ+/YZR9bVQGgearbKl+A1JG+jfse7uWfw8tQSA/5Onjk10DZU4d9D19H/Ih7fXFLtbAQsyFprN1cfHsmFUbjMq2pWwP7k8ofG7qi+Mbk5vub/lTYjs4fWzbZzi/4cv58G/b2Okns1JlMaGGdQQbAYZeUyXezWqmbfr6j+8SFo8xAHoV1Bz4JAz6rTI0vHmt5BngtEnHGCNlkhDxuOAIMmokEGg8Lscl7uAA"
  },
  "undertone": {
    "width": 1920,
    "height": 2877,
    "lqip": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAAAwBwCdASoYACQAPu1oqVEppaOiqrgMATAdiUAWnWZXOCjubGD0lqavfr/uRlc+lqUkxcyOVcU1LugVDOnOBMSlfQAA/lvcBBq1d/tzOlQF4Wb2logGVx0/y40Pe7puxINFEt8A4TNmgQtg5u+tA4xkoP5wm2S5G1Vh+r5qfRy6Tbsa6U9XpXMvoovgOi5uJb6mueIlM+98chvkBM6KOZA43tZHypRT1r4Fk5lz7bHi9qM8evzUrBwhzS2XS3D3GwKxFytELH9pPYXmkChxTiX+2ZE5XdDZ4eoUTA8YTNx9MjTzpHoYVd0cQUOX3jzJ9mScU/nrMpOllYPnCbPOs3UXUb/AAAAA"
  },
  "archetype": {
    "width": 1920,
    "height": 1280,
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYABAAPu1mqk2ppaQiMAgBMB2JQAALfS7K5yoI9yzT30AA/uceMDsSC7GNU2ic/M5tcxPW1fDGf5guAZigQIUDWucy24CgOh5miud3gAA="
  },
  "tryOn": {
    "width": 1920,
    "height": 1280,
    "lqip": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbAC7AYw6yrIIlIWkPdy30cTjgAD+yYFMLgOZCByqzLQjp/EkzAHfUgdkyWpvHTWZDOdMzzUEPCnZhT85rIXS0/uiMI/c1u6UjHxa/Aonpr2tm8DpyHgkMbHsDpgMzTa7Z0YHktEEcCHRepabeH5AzHIoHcUfXNFdoY6gGGNMabdj3Sp8z/mC8KQTkMtmmNO8Rmv0+BxG7zcAAAA="
  },
  "process": {
    "width": 1920,
    "height": 2254,
    "lqip": "data:image/webp;base64,UklGRhQBAABXRUJQVlA4IAgBAABQBgCdASoYABwAPu1sqlEppaOiqAqpMB2JaAC06ywYdBo4MXcLk77LmmTNtAqiJ6bXwb1jF4Zacu6IAAD98HrNExR/k/kG/Ro38s6tPcIeCy8u7EAO+eZ+7shGCw6bkd9zB4CL3QYi4IXUUOEK82eh+r8LixxQsjlow5h75f6R6HKm7DZ3brGDWHVRwlPc8a7quWSpcP9J7e4ejvTBFjYVUiNcB9J3Bll17GyuGk6HcdNIBqk1Ck4Wb1Yt/Q4/PrNPr1HHVZniodSqkoVHyxcX5rytXp17mXwoAyJoyQ233C8pA7IKEF6JVkXlDjSH5KVO6kfDSb84h79kINdd9q4j4XtrXDxEAAA="
  },
  "atelier": {
    "width": 1920,
    "height": 1280,
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdMoR3ACkqoFFZhpMOxXk4AAD+zcq3+DeSHKgAnspDp1fto6vCh3zCjM2o5/DfRu82VDCeY2Uh5DybrZrZC3ItkfOtE+JepkZYcQskPP84wL/VfhWMBA6sIGmnRHXRv43903wJLz/54PtIjQVoNHdTyW15Mn/4dGIjf+27QSxj8xBys21gj6WTrogjVHmNb6wQAAA="
  }
};
