import { Link } from 'wouter';
import ContentPage, { ProseSection } from '@/components/editorial/ContentPage';
import { ROUTES } from '@/config/navigation';

export default function Privacy() {
  return (
    <ContentPage
      eyebrow="Legal"
      title={<>Privacy Policy</>}
      lede="What we collect, why we collect it, and exactly what happens to the photos you upload."
      className="bg-surface-1"
    >
      <ProseSection label="1" title="What we collect">
        <p>
          When you create an account we store your email address and display
          name. When you run a colour analysis we temporarily receive the photo
          you upload, together with the analysis results it produces — your
          colour season, undertone, skin-concern scores, and recommendations.
        </p>
        <p>
          We never sell your personal data, and we do not use it to target ads
          at you.
        </p>
      </ProseSection>

      <ProseSection label="2" title="What happens to your photo">
        <p>
          Your original upload is used once, to run the analysis, and then
          deleted from our servers immediately. The enhanced copy used to build
          your report is kept for a short window so you can download it, and is
          automatically removed within two hours.
        </p>
        <p>
          Photos are processed in part by third-party analysis providers (see
          below). They are never shared publicly, never added to a training
          dataset, and never shown on your public profile.
        </p>
      </ProseSection>

      <ProseSection label="3" title="Analysis providers">
        <p>
          Colour analysis is performed by YouCam (Perfect Corp) and, for
          stylist conversations, replies are generated by Anthropic. Each
          provider receives only what is needed for that specific request — the
          image for a try-on or analysis, or your palette context for a chat
          message — under their own data-processing terms.
        </p>
      </ProseSection>

      <ProseSection label="4" title="Cookies">
        <p>
          We use essential cookies and local storage to keep you signed in and
          to remember your analysis locally in your browser. We do not run
          third-party advertising trackers.
        </p>
      </ProseSection>

      <ProseSection id="cookies" label="5" title="Your rights">
        <p>
          You can request a copy of the data we hold about you, ask us to
          correct or delete it, or withdraw consent at any time. Saved reports
          can be removed from your dashboard at any time.
        </p>
        <p>
          To exercise any of these rights, contact us via the{' '}
          <Link href={ROUTES.contact} className="underline underline-offset-2 hover:text-gold-primary">
            contact page
          </Link>
          .
        </p>
      </ProseSection>

      <ProseSection label="6" title="Contact">
        <p>
          Questions about this policy should be sent through our{' '}
          <Link href={ROUTES.contact} className="underline underline-offset-2 hover:text-gold-primary">
            contact page
          </Link>
          .
        </p>
      </ProseSection>
    </ContentPage>
  );
}
