/**
 * Campaign image pipeline for D'Fashion.
 *
 * Reads the untouched masters in scripts/raw-campaign/ and emits, per base:
 *   - AVIF / WebP / JPEG at 480, 768, 1080, 1440, 1920
 *   - a 24px blurred WebP LQIP (both as a file and a base64 data URI)
 * ...under public/images/campaign/, plus a generated TypeScript manifest
 * (src/lib/campaign-assets.generated.ts) that carries each image's intrinsic
 * dimensions and base64 LQIP for the <picture> placeholder.
 *
 * sharp is a server dependency, so it is resolved through the server
 * workspace rather than duplicated at the repo root.
 *
 *   npm run optimize:images
 */
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const require = createRequire(join(process.cwd(), 'server', 'package.json'));
const sharp = require('sharp');

const SIZES = [480, 768, 1080, 1440, 1920];
const BASES = [
  'opening',
  'closing',
  'season',
  'undertone',
  'archetype',
  'tryOn',
  'process',
  'atelier',
];
const LQIP_WIDTH = 24;

const RAW_DIR = join(process.cwd(), 'scripts', 'raw-campaign');
const OUT_DIR = join(process.cwd(), 'public', 'images', 'campaign');
const MANIFEST = join(process.cwd(), 'src', 'lib', 'campaign-assets.generated.ts');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const assets = {};

  for (const base of BASES) {
    const src = sharp(join(RAW_DIR, `${base}.jpg`));
    const meta = await src.metadata();
    const width = meta.width ?? 0;
    const height = meta.height ?? 0;

    const lqip = await src
      .clone()
      .resize({ width: LQIP_WIDTH })
      .webp({ quality: 40 })
      .toBuffer();
    await writeFile(join(OUT_DIR, `${base}-lqip.webp`), lqip);

    for (const w of SIZES) {
      const resized = src.clone().resize({ width: w });
      const [avif, webp, jpeg] = await Promise.all([
        resized.clone().avif({ quality: 50, effort: 4 }).toBuffer(),
        resized.clone().webp({ quality: 75, effort: 4 }).toBuffer(),
        resized.clone().jpeg({ quality: 72, mozjpeg: true }).toBuffer(),
      ]);
      await Promise.all([
        writeFile(join(OUT_DIR, `${base}-${w}.avif`), avif),
        writeFile(join(OUT_DIR, `${base}-${w}.webp`), webp),
        writeFile(join(OUT_DIR, `${base}-${w}.jpg`), jpeg),
      ]);
    }

    assets[base] = {
      width,
      height,
      lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
    };
    console.log(`✓ ${base}  ${width}×${height}`);
  }

  // Social share card (og:image / twitter:image), 1200×630 centred crop.
  const og = await sharp(join(RAW_DIR, 'opening.jpg'))
    .resize(1200, 630, { fit: 'cover', position: 'centre' })
    .jpeg({ quality: 82, mozjpeg: true })
    .toBuffer();
  await writeFile(join(OUT_DIR, 'opening-og.jpg'), og);
  console.log('✓ og:image  opening-og.jpg  1200×630');

  const manifest = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Re-run \`npm run optimize:images\` after replacing any campaign master.

export interface CampaignAsset {
  width: number;
  height: number;
  lqip: string;
}

export const CAMPAIGN_ASSETS: Record<string, CampaignAsset> = ${JSON.stringify(
    assets,
    null,
    2,
  )};
`;
  await writeFile(MANIFEST, manifest);
  console.log(`\nWrote ${MANIFEST}`);
  console.log(`Wrote ${OUT_DIR} (${BASES.length} bases × ${SIZES.length} sizes × 3 formats + LQIPs + og:image)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
